"""
app.py (Weather Intelligence additions)
----------------------------------------
NOTE: this file contains only the NEW weather-related pieces
(`/weather/sync`, `/weather/search`) meant to be merged into the
existing project's `app.py`, next to the existing `/news/sync` and
other routes. It's written to be self-contained/runnable on its own for
testing, but nothing here touches existing news endpoints or code.

Endpoints:
    POST /weather/sync
        Body: {"locations": ["Chicago, IL", "Austin, TX"], "limit": 50}
        Harvests + normalizes + upserts weather documents. Returns a count.

    POST /weather/search
        Body: {"query": "risk of flooding near rivers", "top_k": 5}
        Cosine-similarity search over weather_embeddings via pgvector's
        `<=>` operator. Optional "source_type": "alert" | "forecast" filter.

    GET /weather/search?query=...&top_k=5
        Same retrieval, plus a basic RAG natural-language summary of the
        top results generated by an LLM.
"""

import logging

from flask import Flask, jsonify, render_template, request

import lakebase
import weather_client

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = Flask(__name__)

# Ensure schema exists at startup (idempotent — safe to call every boot).
lakebase.ensure_weather_schema()

# Load the embedding model once at module level, not per-request.
_embedding_model = None


def get_embedding_model():
    global _embedding_model
    if _embedding_model is None:
        from sentence_transformers import SentenceTransformer

        logger.info("Loading query embedding model: sentence-transformers/all-MiniLM-L6-v2")
        _embedding_model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
    return _embedding_model


def embed_query(text: str) -> list[float]:
    model = get_embedding_model()
    vector = model.encode([text], show_progress_bar=False, normalize_embeddings=True)[0]
    return vector.tolist()

# ---------------------------------------------------------------------------
# Root / health check
# ---------------------------------------------------------------------------

@app.route("/", methods=["GET"])
def index():
    """
    Landing route so the bare app URL doesn't 404. Also doubles as a
    lightweight health check target.
    """
    return jsonify(
        {
            "app": "weather-intelligence",
            "status": "ok",
            "endpoints": {
                "GET /weather": "Browser UI: sync panel + semantic search",
                "POST /weather/sync": 'Body: {"locations": [...], "limit": 50}',
                "POST /weather/search": 'Body: {"query": "...", "top_k": 5}',
                "GET /weather/search": "Query params: query, top_k, source_type",
            },
        }
    )


@app.route("/healthz", methods=["GET"])
def healthz():
    return jsonify({"status": "ok"})


@app.route("/weather", methods=["GET"])
def weather_ui():
    """Browser UI: sync panel + semantic search (templates/weather.html)."""
    return render_template("weather.html")


# ---------------------------------------------------------------------------
# POST /weather/sync
# ---------------------------------------------------------------------------

@app.route("/weather/sync", methods=["POST"])
def weather_sync():
    body = request.get_json(silent=True) or {}
    locations = body.get("locations")
    limit = body.get("limit", 50)

    if not locations or not isinstance(locations, list):
        return jsonify({"error": "'locations' must be a non-empty list of strings"}), 400

    try:
        limit = int(limit)
    except (TypeError, ValueError):
        return jsonify({"error": "'limit' must be an integer"}), 400
    limit = max(1, min(limit, 500))

    try:
        documents = weather_client.harvest(locations, limit=limit)
        synced_count = lakebase.upsert_weather_documents(documents)
    except Exception as exc:  # noqa: BLE001
        logger.exception("weather_sync failed")
        return jsonify({"error": str(exc)}), 500

    return jsonify({"synced": synced_count, "locations": locations})


# ---------------------------------------------------------------------------
# Retrieval (shared by POST and GET /weather/search)
# ---------------------------------------------------------------------------

SEARCH_SQL = """
SELECT d.id AS document_id, d.location, d.headline, d.narrative_text,
       d.source_type, e.chunk_text,
       1 - (e.embedding <=> %s::vector) AS similarity
FROM weather_embeddings e
JOIN weather_documents d ON d.id = e.document_id
{where_clause}
ORDER BY e.embedding <=> %s::vector
LIMIT %s;
"""


def run_similarity_search(query: str, top_k: int, source_type: str | None = None) -> list[dict]:
    query_vector = embed_query(query)

    where_clause = ""
    params = [query_vector]
    if source_type:
        where_clause = "WHERE d.source_type = %s"
        params.append(source_type)
    params.extend([query_vector, top_k])

    sql = SEARCH_SQL.format(where_clause=where_clause)

    with lakebase.get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(sql, params)
            rows = cur.fetchall()

    return [
        {
            "location": row["location"],
            "headline": row["headline"],
            "source_type": row["source_type"],
            "chunk_text": row["chunk_text"],
            "similarity": float(row["similarity"]),
        }
        for row in rows
    ]


def _validate_query_and_top_k(query, top_k_raw):
    """Shared validation/clamping for both POST and GET search handlers."""
    if not query or not isinstance(query, str) or not query.strip():
        return None, None, ("'query' is required and must be a non-empty string", 400)

    try:
        top_k = int(top_k_raw) if top_k_raw is not None else 5
    except (TypeError, ValueError):
        return None, None, ("'top_k' must be an integer", 400)

    top_k = max(1, min(top_k, 20))  # clamp to 1-20 per spec
    return query.strip(), top_k, None


def _weather_embeddings_is_empty() -> bool:
    with lakebase.get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute("SELECT EXISTS (SELECT 1 FROM weather_embeddings LIMIT 1) AS has_rows;")
            row = cur.fetchone()
    return not row["has_rows"]


# ---------------------------------------------------------------------------
# POST /weather/search
# ---------------------------------------------------------------------------

@app.route("/weather/search", methods=["POST"])
def weather_search():
    body = request.get_json(silent=True) or {}
    query, top_k, error = _validate_query_and_top_k(body.get("query"), body.get("top_k"))
    if error:
        message, status = error
        return jsonify({"error": message}), status

    source_type = body.get("source_type")
    if source_type not in (None, "alert", "forecast"):
        return jsonify({"error": "'source_type' must be 'alert' or 'forecast'"}), 400

    if _weather_embeddings_is_empty():
        return jsonify({"results": [], "message": "No weather data has been synced/embedded yet."})

    try:
        results = run_similarity_search(query, top_k, source_type=source_type)
    except Exception as exc:  # noqa: BLE001
        logger.exception("weather_search failed")
        return jsonify({"error": str(exc)}), 500

    return jsonify({"results": results})


# ---------------------------------------------------------------------------
# GET /weather/search  (basic RAG variant)
# ---------------------------------------------------------------------------

def generate_rag_summary(query: str, results: list[dict]) -> str:
    """
    Very small RAG summary generator: stitches the top result chunks
    into a prompt and asks an LLM (Anthropic API) for a short natural-
    language synthesis. Falls back to a plain extractive summary if no
    ANTHROPIC_API_KEY is configured, so this endpoint still works without
    extra setup.
    """
    if not results:
        return "No relevant weather information was found for this query."

    context = "\n\n".join(
        f"- [{r['source_type']}] {r['location']} — {r['headline']}: {r['chunk_text']}"
        for r in results
    )

    import os

    if not os.environ.get("ANTHROPIC_API_KEY"):
        top = results[0]
        return (
            f"Top match ({top['location']}, {top['source_type']}): "
            f"{top['headline']}. {top['chunk_text'][:280]}"
        )

    try:
        import anthropic

        client = anthropic.Anthropic()
        message = client.messages.create(
            model="claude-sonnet-4-6",
            max_tokens=300,
            messages=[
                {
                    "role": "user",
                    "content": (
                        f"Question: {query}\n\n"
                        f"Relevant weather documents:\n{context}\n\n"
                        "Write a short (3-4 sentence) natural-language summary "
                        "answering the question using only the documents above."
                    ),
                }
            ],
        )
        return "".join(block.text for block in message.content if block.type == "text")
    except Exception as exc:  # noqa: BLE001
        logger.warning("RAG summary generation failed, falling back to extractive: %s", exc)
        top = results[0]
        return f"Top match ({top['location']}): {top['headline']}. {top['chunk_text'][:280]}"


@app.route("/weather/search", methods=["GET"])
def weather_search_rag():
    query, top_k, error = _validate_query_and_top_k(
        request.args.get("query"), request.args.get("top_k")
    )
    if error:
        message, status = error
        return jsonify({"error": message}), status

    source_type = request.args.get("source_type")
    if source_type not in (None, "alert", "forecast"):
        return jsonify({"error": "'source_type' must be 'alert' or 'forecast'"}), 400

    if _weather_embeddings_is_empty():
        return jsonify(
            {"results": [], "summary": "No weather data has been synced/embedded yet."}
        )

    try:
        results = run_similarity_search(query, top_k, source_type=source_type)
        summary = generate_rag_summary(query, results)
    except Exception as exc:  # noqa: BLE001
        logger.exception("weather_search_rag failed")
        return jsonify({"error": str(exc)}), 500

    return jsonify({"results": results, "summary": summary})


if __name__ == "__main__":
    import os

    port = int(os.environ.get("DATABRICKS_APP_PORT", 5000))
    app.run(host="0.0.0.0", port=port)