"""
Plain-Python (psycopg2-based) embedding ingestion for weather_documents.

Pipeline:
1. Read weather_documents rows that do not yet have embeddings for the
   current content_hash.
2. Chunk narrative_text using a sliding window:
      CHUNK_SIZE = 800
      CHUNK_OVERLAP = 100
3. Embed each chunk using:
      sentence-transformers/all-MiniLM-L6-v2
   producing 384-dimensional vectors.
4. Batch-upsert embeddings into weather_embeddings using psycopg2.

Important schema assumption:

weather_documents
    id              TEXT

weather_embeddings
    id              BIGINT          -- generated by PostgreSQL
    document_id     TEXT            -- FK -> weather_documents.id
    source_type     ...
    chunk_index     ...
    chunk_text      TEXT
    content_hash    ...
    embedding       VECTOR(384)
    model_name      ...

The embedding table has a UNIQUE constraint on:
    (document_id, chunk_index)

Therefore the PostgreSQL-generated BIGINT `id` is intentionally NOT supplied
by this script.

This makes the ingestion compatible with the current Lakebase schema and
keeps re-runs idempotent through:
    ON CONFLICT (document_id, chunk_index) DO UPDATE

Run directly:

    python ingest_weather_embeddings.py

Optional:

    python ingest_weather_embeddings.py --batch-size 500
"""

import argparse
import logging
from typing import Optional

from psycopg2.extras import execute_values

from lakebase import get_connection


# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

DEFAULT_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"
EMBEDDING_DIM = 384

DEFAULT_CHUNK_SIZE = 800
DEFAULT_CHUNK_OVERLAP = 100
DEFAULT_BATCH_SIZE = 500


# ---------------------------------------------------------------------------
# SQL
# ---------------------------------------------------------------------------

# A document needs embedding when there is no embedding row for the same
# document_id + current content_hash.
#
# This handles:
#   1. documents that have never been embedded
#   2. documents whose narrative_text/content_hash changed
#
# We intentionally do NOT use weather_embeddings.id here because that column
# is a PostgreSQL-generated BIGINT primary key.
FETCH_UNEMBEDDED_SQL = """
SELECT
    d.id,
    d.source_type,
    d.narrative_text,
    d.content_hash
FROM weather_documents AS d
WHERE d.narrative_text IS NOT NULL
  AND length(trim(d.narrative_text)) > 0
  AND NOT EXISTS (
      SELECT 1
      FROM weather_embeddings AS e
      WHERE e.document_id = d.id
        AND e.content_hash = d.content_hash
  );
"""


# IMPORTANT:
#
# `id` is intentionally omitted.
#
# PostgreSQL generates weather_embeddings.id automatically.
#
# The existing UNIQUE constraint:
#
#     weather_embeddings_document_id_chunk_index_key
#
# is used for idempotent upsert.
UPSERT_EMBEDDINGS_SQL = """
INSERT INTO weather_embeddings
(
    document_id,
    source_type,
    chunk_index,
    chunk_text,
    content_hash,
    embedding,
    model_name
)
VALUES %s
ON CONFLICT (document_id, chunk_index)
DO UPDATE SET
    source_type = EXCLUDED.source_type,
    chunk_text = EXCLUDED.chunk_text,
    content_hash = EXCLUDED.content_hash,
    embedding = EXCLUDED.embedding,
    model_name = EXCLUDED.model_name,
    created_at = now();
"""


# The order MUST match the INSERT column list above:
#
# document_id,
# source_type,
# chunk_index,
# chunk_text,
# content_hash,
# embedding,
# model_name
#
# The embedding is converted to PostgreSQL's pgvector representation.
EMBEDDING_TEMPLATE = """
(
    %s,
    %s,
    %s,
    %s,
    %s,
    %s::vector,
    %s
)
"""


# ---------------------------------------------------------------------------
# Chunking
# ---------------------------------------------------------------------------

def chunk_text(
    text: str,
    chunk_size: int = DEFAULT_CHUNK_SIZE,
    overlap: int = DEFAULT_CHUNK_OVERLAP,
) -> list[str]:
    """
    Split text into overlapping sliding-window chunks.

    Example:
        chunk_size = 800
        overlap = 100

    The next chunk starts 700 characters after the previous chunk.

    A document shorter than chunk_size becomes one chunk.
    """

    if chunk_size <= 0:
        raise ValueError("chunk_size must be greater than 0")

    if overlap < 0:
        raise ValueError("chunk_overlap cannot be negative")

    if overlap >= chunk_size:
        raise ValueError(
            "chunk_overlap must be smaller than chunk_size"
        )

    text = text.strip()

    if not text:
        return []

    if len(text) <= chunk_size:
        return [text]

    step = chunk_size - overlap

    chunks = []

    for start in range(0, len(text), step):
        chunk = text[start:start + chunk_size].strip()

        if chunk:
            chunks.append(chunk)

        if start + chunk_size >= len(text):
            break

    return chunks


# ---------------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------------

def fetch_unembedded_documents(cur) -> list[dict]:
    """
    Fetch weather documents that need a new/current embedding.
    """

    cur.execute(FETCH_UNEMBEDDED_SQL)

    columns = [description.name for description in cur.description]

    return [
        dict(zip(columns, row))
        for row in cur.fetchall()
    ]


# ---------------------------------------------------------------------------
# Embedding model
# ---------------------------------------------------------------------------

_model = None
_model_name_loaded: Optional[str] = None


def get_model(model_name: str = DEFAULT_MODEL_NAME):
    """
    Lazily load the SentenceTransformer model once per process.
    """

    global _model
    global _model_name_loaded

    if _model is None or _model_name_loaded != model_name:
        from sentence_transformers import SentenceTransformer

        logger.info(
            "Loading embedding model: %s",
            model_name,
        )

        _model = SentenceTransformer(model_name)
        _model_name_loaded = model_name

    return _model


def embed_chunks(
    chunks: list[str],
    model_name: str = DEFAULT_MODEL_NAME,
) -> list[list[float]]:
    """
    Generate normalized embeddings for a list of text chunks.
    """

    if not chunks:
        return []

    model = get_model(model_name)

    vectors = model.encode(
        chunks,
        show_progress_bar=False,
        normalize_embeddings=True,
    )

    result = [vector.tolist() for vector in vectors]

    # Safety check: make sure the embedding dimension matches
    # the VECTOR(384) database column.
    for index, vector in enumerate(result):
        if len(vector) != EMBEDDING_DIM:
            raise ValueError(
                f"Embedding dimension mismatch at chunk {index}: "
                f"expected {EMBEDDING_DIM}, got {len(vector)}"
            )

    return result


# ---------------------------------------------------------------------------
# Main ingestion
# ---------------------------------------------------------------------------

def run(
    batch_size: int = DEFAULT_BATCH_SIZE,
    model_name: str = DEFAULT_MODEL_NAME,
    chunk_size: int = DEFAULT_CHUNK_SIZE,
    chunk_overlap: int = DEFAULT_CHUNK_OVERLAP,
) -> int:
    """
    Full embedding ingestion pass.

    Returns:
        Number of embedding rows processed.
    """

    if batch_size <= 0:
        raise ValueError("batch_size must be greater than 0")

    logger.info("Starting weather embedding ingestion.")
    logger.info("Model: %s", model_name)
    logger.info("Chunk size: %d", chunk_size)
    logger.info("Chunk overlap: %d", chunk_overlap)
    logger.info("Batch size: %d", batch_size)

    total_written = 0

    with get_connection() as conn:

        # ---------------------------------------------------------------
        # 1. Fetch documents
        # ---------------------------------------------------------------

        with conn.cursor() as cur:
            documents = fetch_unembedded_documents(cur)

        logger.info(
            "Found %d document(s) needing embeddings.",
            len(documents),
        )

        if not documents:
            logger.info(
                "No documents require embedding."
            )
            return 0

        # ---------------------------------------------------------------
        # 2. Chunk + embed
        # ---------------------------------------------------------------

        rows_to_write = []

        for doc in documents:

            document_id = doc["id"]
            source_type = doc["source_type"]
            narrative_text = doc["narrative_text"]
            content_hash = doc["content_hash"]

            chunks = chunk_text(
                narrative_text,
                chunk_size=chunk_size,
                overlap=chunk_overlap,
            )

            if not chunks:
                continue

            logger.info(
                "Document %s: %d chunk(s)",
                document_id,
                len(chunks),
            )

            vectors = embed_chunks(
                chunks,
                model_name=model_name,
            )

            # -----------------------------------------------------------
            # 3. Build database rows
            # -----------------------------------------------------------

            for chunk_index, (chunk, vector) in enumerate(
                zip(chunks, vectors)
            ):

                rows_to_write.append(
                    (
                        document_id,
                        source_type,
                        chunk_index,
                        chunk,
                        content_hash,
                        vector,
                        model_name,
                    )
                )

        logger.info(
            "Writing %d embedding row(s).",
            len(rows_to_write),
        )

        if not rows_to_write:
            logger.info(
                "No embedding rows were generated."
            )
            return 0

        # ---------------------------------------------------------------
        # 4. Batch upsert
        # ---------------------------------------------------------------

        with conn.cursor() as cur:

            for start in range(
                0,
                len(rows_to_write),
                batch_size,
            ):

                batch = rows_to_write[
                    start:start + batch_size
                ]

                execute_values(
                    cur,
                    UPSERT_EMBEDDINGS_SQL,
                    batch,
                    template=EMBEDDING_TEMPLATE,
                )

                total_written += len(batch)

                logger.info(
                    "Wrote batch of %d "
                    "(running total: %d)",
                    len(batch),
                    total_written,
                )

        # Explicit commit so the batch is persisted.
        conn.commit()

    logger.info(
        "Embedding ingestion completed successfully. "
        "Processed %d embedding row(s).",
        total_written,
    )

    return total_written


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Generate weather document embeddings and store them in Lakebase."
    )

    parser.add_argument(
        "--batch-size",
        type=int,
        default=DEFAULT_BATCH_SIZE,
        help=f"Number of rows written per batch. Default: {DEFAULT_BATCH_SIZE}",
    )

    parser.add_argument(
        "--embedding-model",
        default=DEFAULT_MODEL_NAME,
        help=f"SentenceTransformer model. Default: {DEFAULT_MODEL_NAME}",
    )

    parser.add_argument(
        "--chunk-size",
        type=int,
        default=DEFAULT_CHUNK_SIZE,
        help=f"Chunk size in characters. Default: {DEFAULT_CHUNK_SIZE}",
    )

    parser.add_argument(
        "--chunk-overlap",
        type=int,
        default=DEFAULT_CHUNK_OVERLAP,
        help=f"Chunk overlap in characters. Default: {DEFAULT_CHUNK_OVERLAP}",
    )

    args = parser.parse_args()

    run(
        batch_size=args.batch_size,
        model_name=args.embedding_model,
        chunk_size=args.chunk_size,
        chunk_overlap=args.chunk_overlap,
    )


if __name__ == "__main__":
    main()